# This is a basic workflow to help you get started with Actions

name: issue and pull_request

# Controls when the workflow will run
on: [push, pull_request]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 30
          days-before-close: 5
          stale-issue-message: This issue is stale because it has been open 30 days with no activity. Leave a comment or this will be closed in 5 days.
          stale-pr-message: This PR is stale because it has been open 30 days with no activity. Leave a comment or this will be closed in 5 days
          stale-issue-label: no-issue-activity
          stale-pr-label: no-pr-activity
          operations-per-run: 30
