# This is a basic workflow to help you get started with Actions

name: issue and pull_request

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
